/**
 * Generator for the Cloudflare Worker entry (`<root>/.flue-vite/_entry.ts`).
 *
 * The entry must be a physical file — wrangler `main` resolves it, and its
 * bare imports (`agents`, `@flue/runtime/*`) must resolve from the USER's
 * node_modules — so this stays generated text rather than a bootstrap module
 * shipped inside `@flue/vite`. It is deliberately thin: all per-agent class
 * mechanics live in `createFlueAgentClass` / `createCloudflareAgentRuntime`
 * (real, tested code in `@flue/runtime`); the generated file only joins the
 * scanned `'use agent'` set to those factories.
 *
 * Ported from the CLI's Cloudflare build plugin
 * (packages/cli/src/lib/build-plugin-cloudflare.ts `generateEntryPoint`),
 * minus workflows, channels, the run registry, and the no-`app.ts` fallback —
 * on the new surface `app.ts` is required and the scan is the registration.
 */
import type { AgentScanResult } from './agent-scan.ts';

export interface GenerateCloudflareEntryOptions {
	/** Absolute path of the user's `app.*` entry (required on the new surface). */
	readonly appEntry: string;
	/** Absolute path of the user's `cloudflare.*` entry, if any. */
	readonly cloudflareEntry: string | undefined;
	/** The scanned `'use agent'` module set. */
	readonly agents: readonly AgentScanResult[];
}

/** Posix-normalize a path for embedding in generated import specifiers. */
function importPath(filePath: string): string {
	return JSON.stringify(filePath.replace(/\\/g, '/'));
}

export function generateCloudflareEntry(options: GenerateCloudflareEntryOptions): string {
	const { appEntry, cloudflareEntry, agents } = options;

	const agentVar = (index: number) => `__flue_agent_${index}__`;

	const agentImports = agents
		.map((agent, index) => `import * as ${agentVar(index)} from ${importPath(agent.filePath)};`)
		.join('\n');

	const scannedAgentEntries = agents
		.map(
			(agent, index) =>
				`\t{ identity: ${JSON.stringify(agent.identity)}, module: ${agentVar(index)} },`,
		)
		.join('\n');

	const agentIdentityEntries = agents
		.map(
			(agent) =>
				`\t${JSON.stringify(agent.identity)}: { bindingName: ${JSON.stringify(agent.bindingName)}, className: ${JSON.stringify(agent.className)} },`,
		)
		.join('\n');

	const agentClassExports = agents
		.map((agent, index) =>
			[
				`export const ${agent.className} = createFlueAgentClass({`,
				`\tAgentBase: Agent,`,
				`\truntime: cloudflareAgents,`,
				`\tclassName: ${JSON.stringify(agent.className)},`,
				`\tagentName: ${JSON.stringify(agent.identity)},`,
				`\textension: ${agentVar(index)}.cloudflare,`,
				`});`,
			].join('\n'),
		)
		.join('\n\n');

	const userCloudflareImport = cloudflareEntry
		? `import * as userCloudflareModule from ${importPath(cloudflareEntry)};\nexport * from ${importPath(cloudflareEntry)};`
		: '';
	const userCloudflareValue = cloudflareEntry ? 'userCloudflareModule' : '{}';
	const reservedCloudflareExportNames = agents.map((agent) => agent.className);

	return `// Auto-generated by @flue/vite (target: cloudflare). Do not edit.
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import { registerApiProvider, registerProvider } from '@flue/runtime';
import {
	Bash,
	bashFactoryToSessionEnv,
	CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH,
	configureFlueRuntime,
	createCloudflareAgentRuntime,
	createFlueContext,
	hasRegisteredProvider,
	InMemoryFs,
	installDevLifecycleLogger,
	registerFlueAgents,
	resolveModel,
} from '@flue/runtime/internal';
import {
	createFlueAgentClass,
	getCloudflareAIBindingApiProvider,
	runWithCloudflareContext,
} from '@flue/runtime/cloudflare/internal';

import userApp from ${importPath(appEntry)};
${userCloudflareImport}
${agentImports}

// ─── Internal provider registrations ────────────────────────────────────────
// User \`app.ts\` imports are hoisted above this body, so a user-supplied
// \`registerProvider('cloudflare', ...)\` runs first; the guard below
// preserves it. The runtime routes registrations without an explicit
// \`gateway\` through Cloudflare's default AI Gateway.

registerApiProvider(getCloudflareAIBindingApiProvider());

if (!hasRegisteredProvider('cloudflare')) {
	registerProvider('cloudflare', {
		api: 'cloudflare-ai-binding',
		binding: env.AI,
	});
}

// ─── Registration ───────────────────────────────────────────────────────────
// The scan IS the registration: every 'use agent' module joins the app.
// \`.route()\` mounts in app.ts are pure routers over this set.

const scannedAgentModules = [
${scannedAgentEntries}
];
const registrations = scannedAgentModules.map(({ identity, module }) => ({
	identity,
	definition: module.default,
	...(module.route !== undefined ? { route: module.route } : {}),
	...(module.attachments !== undefined ? { attachments: module.attachments } : {}),
	...(module.description !== undefined ? { description: module.description } : {}),
}));
registerFlueAgents(registrations);
const agents = registrations.map((registration) => ({
	name: registration.identity,
	definition: registration.definition,
	...(registration.description !== undefined ? { description: registration.description } : {}),
	...(registration.route !== undefined ? { route: registration.route } : {}),
	...(registration.attachments !== undefined ? { attachments: registration.attachments } : {}),
}));
const agentIdentities = {
${agentIdentityEntries}
};

// ─── cloudflare.ts composition ──────────────────────────────────────────────

const userCloudflare = ${userCloudflareValue};
const reservedCloudflareExportNames = new Set(${JSON.stringify(reservedCloudflareExportNames)});
for (const name of Object.keys(userCloudflare)) {
	if (name === 'default') continue;
	if (reservedCloudflareExportNames.has(name)) {
		throw new Error('[flue] cloudflare.ts export "' + name + '" conflicts with a Flue-generated Worker export. Rename the authored export.');
	}
}
const cloudflareHandlers = 'default' in userCloudflare ? userCloudflare.default : {};
if (typeof cloudflareHandlers !== 'object' || cloudflareHandlers === null || Array.isArray(cloudflareHandlers)) {
	throw new Error('[flue] cloudflare.ts default export must be an object containing non-HTTP Worker handlers.');
}
if ('fetch' in cloudflareHandlers) {
	throw new Error('[flue] cloudflare.ts default export must not define fetch. Use app.ts for custom HTTP handling.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
	const fs = new InMemoryFs();
	return bashFactoryToSessionEnv(() => new Bash({
		fs,
		network: { dangerouslyAllowFullInternetAccess: true },
	}));
}

// ─── Agent wiring ───────────────────────────────────────────────────────────

const dispatchQueue = {
	async enqueue(input) {
		const identity = agentIdentities[input.agent];
		const binding = env?.[identity?.bindingName];
		if (!binding) throw new Error('[flue] dispatch() target agent "' + input.agent + '" Durable Object binding is unavailable.');
		const response = await fetchAgent(binding, input.id, new Request('https://flue.invalid' + CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH, {
			method: 'POST',
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify(input),
		}));
		if (!response.ok) throw new Error('[flue] dispatch() target agent "' + input.agent + '" rejected durable admission with status ' + response.status + '.');
		return response.json();
	},
};

function createAgentContextForRequest({ executionStore, instance, agentName, request, initialEventIndex, dispatchId }) {
	return createFlueContext({
		id: instance.name,
		agentName,
		env: instance?.env ?? {},
		req: request,
		initialEventIndex,
		dispatchId,
		agentConfig: { resolveModel },
		createDefaultEnv,
		submissionStore: executionStore.submissions,
	});
}

async function fetchAgent(binding, instanceId, request) {
	return (await getAgentByName(binding, instanceId)).fetch(request);
}

function runWithInstanceContext(doInstance, identity, fn) {
	return runWithCloudflareContext(
		{
			env: doInstance.env,
			storage: doInstance.ctx.storage,
			durableObjectIdentity: {
				bindingName: identity.bindingName,
				className: identity.className,
				name: doInstance.name,
				id: doInstance.ctx.id.toString(),
			},
		},
		fn,
	);
}

const devLifecycle = import.meta.env.DEV ? installDevLifecycleLogger() : undefined;
const cloudflareAgents = createCloudflareAgentRuntime({
	agents,
	createContext: createAgentContextForRequest,
	runWithInstanceContext: (instance, agentName, fn) => runWithInstanceContext(instance, agentIdentities[agentName], fn),
	onInteractionStart: devLifecycle?.onAgentInteractionStart,
});

// ─── Per-agent Durable Object classes ───────────────────────────────────────

${agentClassExports}

// ─── Runtime seed ───────────────────────────────────────────────────────────
// Legacy shape (workflows, channelHandlers, run routing) stays valid until
// Phase 7 removes it; the new surface registers no workflows.

configureFlueRuntime({
	target: 'cloudflare',
	devMode: import.meta.env.DEV,
	temporaryLocalExposure: false,
	agents,
	workflows: [],
	dispatchQueue,
	admitWorkflow: async () => {
		throw new Error('[flue] Internal workflow admission target is not registered.');
	},
	channelHandlers: {},
	routeAgentRequest: async (request, reqEnv, target) => {
		const binding = reqEnv?.[agentIdentities[target.agentName]?.bindingName];
		if (!binding) return null;
		return fetchAgent(binding, target.instanceId, request);
	},
	routeWorkflowRequest: async () => null,
	routeRunRequest: async () => null,
	createRunIndexForRequest: () => undefined,
});

// ─── App composition ────────────────────────────────────────────────────────
// User-supplied app.ts. Its default export owns the entire request pipeline —
// the worker just verifies a fetch method exists and pipes through.

const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
	throw new Error(
		'[flue] app.ts default export must be a Hono app or an object with a fetch(request, env, ctx) method.'
	);
}

export default {
	...cloudflareHandlers,
	fetch(request, env, ctx) {
		return flueApp.fetch(request, env, ctx);
	},
};
`;
}
